### ISSUE TITLE
Can you share us how did you train the encoder for the feature extractor?

### ISSUE THREAD

**Issue by jeonghomin** [caojiezhang/DATSR#12]
For reading DATSR paper , i wonder if you train the encoder with giving jitter augmentation since different distribution between ref and input. 

Does that mean you train the encoder with augmentation or you give augmentation with training main DATSR model?

If so, can you share us how you train the encoder ?

**Comment by djkzxxf** [comment]
Brother, did you use the pre-training model to test the indicators to achieve the results of his paper. I measured that it did not meet the index of his paper, which was a lot worse.

**Comment by jeonghomin** [comment]
You mean the evaluation of PSNR score results really bad? compared to the paper?

**Comment by Orange066** [comment]
> Brother, did you use the pre-training model to test the indicators to achieve the results of his paper. I measured that it did not meet the index of his paper, which was a lot worse.

I also meet this problem, did you solve it?

**Comment by Guohaitao1** [comment]
lack mmsr fiile,how to solve it?

**Comment by jeonghomin** [comment]
Figured it out

**Comment by Guohaitao1** [comment]
Can you send your mmsr package to my email (2319484564@qq.com)? Thanks in advance
