### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by dkkmin0** [caojiezhang/DATSR#15]
I'm trying to study using your model, but I can't seem to find the requirements.txt file no matter how much I search.

**Comment by heng0607** [comment]
You can find it in c2 matching

**Comment by dkkmin0** [comment]
oh... i see  
thanks for your help

**Comment by heng0607** [comment]
> 哦。。。明白了 感谢您的帮助



I would like to ask a question, do you use RTX3090 to configure the environment? I have encountered a problem that cannot be resolved at the moment.

**Comment by dkkmin0** [comment]
hi!
i'm planning to use 4070ti 
but it will be 2024 - feb 
I'm sorry for not being helpful

-----Original Message-----
