### ISSUE TITLE
solve

### ISSUE THREAD

**Issue by ModestTony** [caojiezhang/DATSR#6]

**Comment by ModestTony** [comment]
> Excuse me author, thank you for the work on this paper. I have come across a problem and would like to ask for some advice.
> 
> With the code you provided, I have tried to reproduce this thesis code and for the CUFED5 dataset, my test results are **PSNR/SSIM = 28.50/0.851** with rec_loss and **PSNR/SSIM = 27.76/0.828** with all_loss. I did not change the code and the feature_extraction.pth,restoration_gan.pth and restoration_mse.pth files were downloaded from the path you provided: https://github.com/caojiezhang/DATSR/releases
> 
> Looking forward to your reply.

**Comment by Orange066** [comment]
The PSNR/SSIM values of the code do not match the paper, how did you solve it?
